### ISSUE TITLE
Geliştirme

### ISSUE THREAD

**Issue by northeaster** [cenkkoroglu/flarum-tcno-dogrulama#1]
![image](https://user-images.githubusercontent.com/55854510/82816808-7d2abf00-9ea4-11ea-92c7-f2e3f142a0e3.png)
Eğer hesap doğrulanmış ise bu pencerede doğrulamayı kaldır diye bir seçenek koyulabilir. Yetkililer için istediği hesabın doğrulamasını kendi kaldırabilme seçeneği eklenebilir.
Aynı bilgiler ile çoklu hesapta doğrulama yapılmamalı. Yeni hesap açıp denedim. Aynı bilgiler ile onayı verdi ama tick i vermedi.
Hesabını onaylayanlara ek özellikler verebiliriz. Bazı kategorilere erişme gibi. Mavi tick yerine rol vermek ile yapılabilir evet. Ama bu sefer kullanılarda çok fazla rol oluyor. İlerisi için problem yaratabilir.

**Comment by cenkkoroglu** [comment]
- Identity approved users list implemented for admins 
- Now admin users can remove user's approve
- Migration done for storing identity numbers (hashed by sha1 encryption)
- Verification with the same information was prevented

version 0.0.1 is available

**Comment by northeaster** [comment]
**Development requests:**
- On the user's profile page, they can write the name and surname that I use to verify their account.
- Users should be shown with their surnames hidden. Name and surname should be completely visible to the admins. In the permissions setting, it should be possible to set which roles to grant this authority.
