### ISSUE TITLE
No registration, not logged in

### ISSUE THREAD

**Issue by ghost** [cenkkoroglu/flarum-tcno-dogrulama#3]
While the plugin is active;
- No registration.
- Not logged in.
There is no error log. When I said "inspect element" in my browser, I examined the "network" and "console" sections. No error appears.

https://discuss.flarum.org/d/23968-i-cannot-log-in-on-the-site

**Comment by cenkkoroglu** [comment]
I can create user and login when the plugin is active. This extension does not modify the login/signup modals.

**Comment by ghost** [comment]
Before I could find out what the error was, I wrote it on the flarum site. You can see the answer given in the link. The error was fixed when I removed this extension.

**Comment by cenkkoroglu** [comment]
Yeah I read your post and read given answers, he said that this extension modify the login/signup modal but if you check the repository you can see that there is no action or modify to the login/signup modal. I believe that there is a collision between your extensions and my extension but I can't do anything because I don't know what is the problem. If you open debug mod and get error, I could do something. Sorry my friend.

Here is my composer file:

`{
    "name": "flarum/flarum",
    "description": "Delightfully simple forum software.",
    "type": "project",
    "keywords": [
        "forum",
        "discussion"
    ],
    "homepage": "https://flarum.org/",
    "license": "MIT",
    "authors": [
        {
            "name": "Franz Liedke",
            "email": "franz@develophp.org"
        },
        {
            "name": "Daniel Klabbers",
            "email": "daniel@klabbers.email",
            "homepage": "https://luceos.com"
        },
        {
            "name": "David Sevilla Martin",
            "email": "me+flarum@datitisev.me",
            "homepage": "https://datitisev.me"
        },
        {
            "name": "Clark Winkelmann",
            "email": "clark.winkelmann@gmail.com",
            "homepage": "https://clarkwinkelmann.com"
        },
        {
            "name": "Matthew Kilgore",
            "email": "matthew@kilgore.dev"
        }
    ],
    "support": {
        "issues": "https://github.com/flarum/core/issues",
        "source": "https://github.com/flarum/flarum",
        "docs": "https://flarum.org/docs/"
    },
    "require": {
        "cenkkoroglu/tcno-dogrulama": "@dev",
        "cenkkoroglu/youtube-embed": "@dev",
        "flarum/approval": "^0.1.0",
        "flarum/auth-facebook": "^0.1.0",
        "flarum/auth-github": "^0.1.0",
        "flarum/auth-twitter": "^0.1.0",
        "flarum/bbcode": "^0.1.0",
        "flarum/core": "^0.1.0",
        "flarum/emoji": "^0.1.0",
        "flarum/flags": "^0.1.0",
        "flarum/lang-english": "^0.1.0",
        "flarum/likes": "^0.1.0",
        "flarum/lock": "^0.1.0",
        "flarum/markdown": "^0.1.0",
        "flarum/mentions": "^0.1.0",
        "flarum/pusher": "^0.1.0",
        "flarum/statistics": "^0.1.0",
        "flarum/sticky": "^0.1.0",
        "flarum/subscriptions": "^0.1.0",
        "flarum/suspend": "^0.1.0",
        "flarum/tags": "^0.1.0"
    },
	"repositories": [
        {
            "type": "path",
            "url": "extensions/*/"
        }
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "beta",
    "prefer-stable": true
}
`

**Comment by ghost** [comment]
It seems like no problem right now. See: https://forum.sourceturk.net
